### ISSUE TITLE
xdg is deprecated, renamed to xdg-base-dirs

### ISSUE THREAD

**Issue by jonathan-berezin** [Textualize/frogmouth#100]
The PyPI project description for xdg says the following:

"""xdg has been renamed to xdg-base-dirs due to an import collision with PyXDG. Therefore the xdg package is deprecated. Install xdg-base-dirs instead.
"""

The PyPI project description for xdg-base-dirs makes a corresponding warning.

References:
    https://pypi.org/project/xdg/
    https://pypi.org/project/xdg-base-dirs/

**Comment by davep** [comment]
`xdg-base-dirs` is Python>=3.10; Frogmouth supports Python 3.8 and above. There are no substantial changes in `xdg-base-dirs` vs `xdg` and pinning to `xdg` [is recommended by the maintainer themselves](https://github.com/srstevenson/xdg-base-dirs/issues/142#issuecomment-1461034985).

If/when Frogmouth becomes Python>=3.10 it will likely swap to `xdg-base-dirs`.

**Comment by jonathan-berezin** [comment]
Awesome! The more you know. I was browsing/admiring the codebase here, hadn't encountered xdg before, looked it up, and thought it was the right thing to do to raise a flag! I'm glad there's no issue.

**Comment by davep** [comment]
No worries: much better to raise the issue and be sure, so very much appreciated.

**Comment by gl-yziquel** [comment]
@jonathan-berezin I made a PR for that change you requested: https://github.com/Textualize/frogmouth/pull/113.

I need that to get it packaged as a debian package in my local workflow (and get xdg-base-dirs packaged too).

@davep It does indeed requires python >= 3.10. What is wrong with not being 3.8 compatible ? If 3.8 is a must, then I guess it should not be too much of a problem to use pyxdg and not xdg-base-dirs. At least until frogmouth gets 3.10 compatible.

**Comment by davep** [comment]
@gl-yziquel Back when this issue was raised Python 3.8 wasn't yet EOL, and the brief for Frogmouth was to stay compatible with all supported Python versions (like Textual).

I can't speak to if this is still a requirement as I'm no longer a maintainer of this application.

**Comment by gl-yziquel** [comment]
@davep who is the maintainer of this application ?

**Comment by davep** [comment]
Sorry, I don't know; you'd probably need to direct that question at the company who own the organisation.

**Comment by gl-yziquel** [comment]
@davep Hmmmhh.... smell like politics. OK. Thank you.

**Comment by davep** [comment]
I'm afraid your sense of smell is off. I literally don't know the answer so I can't give you something I'm not in possession of. I have however pointed you to where you can get the answer.

**Comment by gl-yziquel** [comment]
@davep thanks.
