### ISSUE TITLE
strikethrough formatting not rendered

### ISSUE THREAD

**Issue by josephhaaga** [Textualize/frogmouth#106]
Looks like `~~strikethrough~~` formatted text doesn't render as expected

<img width="1405" alt="image" src="https://github.com/user-attachments/assets/34c8dd75-e7ba-4932-b39c-d71c30fa73e2">

**Comment by TomJGooding** [comment]
What terminal are you using? It might be that it doesn't support strikethrough, here's a simple test:

```
echo -e "\e[9mstrikethrough\e[0m"
```

**Comment by josephhaaga** [comment]
> What terminal are you using? It might be that it doesn't support strikethrough, here's a simple test:
> 
> ```
> echo -e "\e[9mstrikethrough\e[0m"
> ```

That's it! My mistake :)

FWIW: tmux inside Terminal.app with the Hack Nerd Font Mono Regular 14
