### ISSUE TITLE
Feature Request: Vim bindings, just hjkl navigation even

### ISSUE THREAD

**Issue by gigatexal** [Textualize/frogmouth#14]
As the title suggests it would be awesome if I could navigate with the vim bindings .

**Comment by davep** [comment]
Already in there for the next update. :-)

**Comment by gigatexal** [comment]
Beautiful!

**Comment by davep** [comment]
Amusingly, it's sort of supported for switching tabs in the navigation pane -- vi-friendly versions of left and right work there (also a and d for the gamers amongst is too). I was quite proud of adding that.

Then totally forgot to do the same for the actual document pane. (╯°□°）╯︵ ┻━┻

**Comment by gigatexal** [comment]
Again, thank you 100x. 

it's the first thing I grab or my fingers go to is: can I navigate using vim-mode. I do love the idea of the tool though. anything that helps me stay in the terminal is amazing and so is textualize
