### ISSUE TITLE
YAML front matter

### ISSUE THREAD

**Issue by minimaxir** [Textualize/frogmouth#15]
YAML front matter is a common feature for static site/blog generators and Python documentation tools, but frogmouth handles it weirdly. Unclear if it's within scope.

The front matter for one of my blog posts in VS Code:

<img width="703" alt="Screenshot 2023-04-30 at 2 10 50 PM" src="https://user-images.githubusercontent.com/2179708/235376409-f75eda99-2d60-4f88-8556-39f40cd3b11e.png">

The front matter in frogmouth:

<img width="508" alt="Screenshot 2023-04-30 at 2 05 12 PM" src="https://user-images.githubusercontent.com/2179708/235376333-e5f51a3a-1163-440d-88bd-82e297a92ae5.png">

**Comment by davep** [comment]
At this stage we're aiming to handle documents that conform to [CommonMark](https://commonmark.org/), or thereabouts. But I can see that it would be handy to see about handling this too; I'll keep this in mind.

**Comment by willmcgugan** [comment]
This should probably be something supported by the Textual Markdown widget.

**Comment by davep** [comment]
@willmcgugan Yup, experimented with it briefly this morning and have it working; albeit by "ignoring" the front-matter for now; hence https://github.com/Textualize/textual/issues/2440.

**Comment by davep** [comment]
See also #20 for a more general take on this (eg: footnotes could be handy, etc).

**Comment by davep** [comment]
Now that https://github.com/Textualize/textual/pull/2803 is part of Textual it should be easy enough to pull in the relevant plugin and make use of it.

**Comment by davep** [comment]
As of #96 frontmatter won't be displayed within the document view.
