### ISSUE TITLE
Add support to launch $EDITOR?

### ISSUE THREAD

**Issue by khughitt** [Textualize/frogmouth#18]
If so, binding it to "e" would be a really convenient way to open the document in an editor.

At least on Linux, [click.edit](https://click.palletsprojects.com/en/8.1.x/utils/#launching-editors) works pretty well for this.

```
click.edit(filename=...)
```

I haven't tried it on other systems though so I'm sure there could be some limitations.

Thanks again!

Cheers,
Keith

**Comment by davep** [comment]
Closing as a duplicate of #11.

**Comment by khughitt** [comment]
Thought I checked for this, too. Sorry for missing that!
