### ISSUE TITLE
Add history cleaning support

### ISSUE THREAD

**Issue by davep** [Textualize/frogmouth#24]
When in the history view, give the user the ability to remove individual items from history, or just clear the whole thing.

**Comment by jjbiggins** [comment]
Is this project open for contributions? I noticed there have only been two contributors, and of that, the majority of commits are from you. If the project is open to contributions, I found a few of the open enhancements interesting.

**Comment by davep** [comment]
Thanks for your interest @jjbiggins -- at the moment I'm still feeling my way with this and it's also fulfilling the role of letting me experiment with and try out new things for Textual itself; as such, outside of typos and obvious bug fixes, I'm not really looking for contributions at the moment. Mainly because anything anyone contributes may end up being removed or overwritten with big internal changes and I'd sooner not do that.

Over the coming months though, when things settle down, sure.

Thanks again.

**Comment by jjbiggins** [comment]
Sounds good, @davep. I appreciate the response.
