### ISSUE TITLE
Toggle table of contents (or other menu items)

### ISSUE THREAD

**Issue by gennaro-tedesco** [Textualize/frogmouth#32]
Thank you for `frogmouth`, it's awesome!

At the moment a set of shortcuts are allowed, say `ctrl-t/n/b/l` to show specific items of the menu: would it be possible to make such keymaps _toggle_ rather than just open? Practically speaking, if I use `ctrl-t` to quickly show the table of content, I would expect to be able to quickly hide it back again without moving the hands from the keys (instead of having to use `ctrl-n` to toggle-hide the whole menu)

**Comment by davep** [comment]
Originally an action within one of those panes would auto-close the navigation sidebar; so selecting a file from the bookmarks would auto-close and get you back to reading. That got changed just before release. I was wanting to make that behaviour optionally available again. My thinking being, <kbd>Ctrl</kbd>+<kbd>N</kbd> toggles the navigation open and closed, the others are about getting you to the specific pane (so auto-open-and-focus) and selecting something would close if you had that open switched on.

But, yeah, I can also see the value in making them all toggles. I'll keep it in mind when I come to tidying this up.

And thanks for your kind words, glad you're enjoying it. :-)

**Comment by gennaro-tedesco** [comment]
> so selecting a file from the bookmarks would auto-close and get you back to reading.

this would only work for the bookmarks (or history), specifically: for the table of contents after selecting a certain part of the README I want to skip to, the left panel is still open.

Obviously this is just nitpicking, mentioning it in case some other users want to refer to this too :)

**Comment by davep** [comment]
Not nitpicking at all! It's useful to know different people's preferences, habits, expectations and muscle memory!
