### ISSUE TITLE
OSError could not install package

### ISSUE THREAD

**Issue by AddictArts** [Textualize/frogmouth#38]
Any chance for Windows support?

Thanks

**Comment by davep** [comment]
I've installed and run it fine on Windows. Do you think you could give more information please? Windows version. How you installed it. The exact error message with any traceback, and what actually gave the error. Anything else you think may help.

**Comment by AddictArts** [comment]
The error I got on a `pip install frogmouth` was `OSError` package not supported on OS.

I then did `pip install textual` first in an elevated powershell. That worked. Then in an elevated powershell `pip install frogmouth` worked. Just did these steps. Thanks

**Comment by davep** [comment]
What version of Windows, Python and pip? As I've not seen this myself on Windows 11 and I'm not aware of anything that would cause that error more detail would be better.

**Comment by davep** [comment]
Assuming this is fixed by/for the user in their own environment.

**Comment by AddictArts** [comment]
Windows 10, python 311 installed with Strawberry

**Comment by davep** [comment]
I don't think I know what `Strawberry` is; could you give more details?
