### ISSUE TITLE
Feature Request: Package & Release on Homebrew

### ISSUE THREAD

**Issue by joel-aws** [Textualize/frogmouth#43]
First, this is an **awesome** tool -- thank you for creating and maintaining it!

Would you be able to [add this to Homebrew](https://docs.brew.sh/Adding-Software-to-Homebrew) to make system-wide mac installs even easier?

**Comment by davep** [comment]
Thanks, and, yes, it's something I'd like to do at some point. At least make it so you can "tap" it (if that's what it's called, I always find the terminology used by Homebrew hard to remember) from here to start with.

**Comment by vassudanagunta** [comment]
You can get a list of existing Homebrew formula that depend on python:

``` bash
brew uses python --eval-all
```

Might be able to use one of those as a starting point.
