### ISSUE TITLE
No module named 'frogmouth'

### ISSUE THREAD

**Issue by RomanoZumbe** [Textualize/frogmouth#45]
I installed it via on Arch from the AUR via yay. After starting I just get the following error message:

Traceback (most recent call last):
  File "/usr/bin/frogmouth", line 5, in <module>
    from frogmouth.app.app import run
ModuleNotFoundError: No module named 'frogmouth'

**Comment by davep** [comment]
Unfortunately I don't know Arch, AUR or yay so it's very hard to say what the issue is here. Is this some third party packaging system?

**Comment by RomanoZumbe** [comment]
It is just a set of instructions to build the software. But I'll remove it for now and try to install via pip. This is probably more a problem of whoever created the AUR script

**Comment by RomanoZumbe** [comment]
Installing via PIP didn't work either. When installing as user I didn't have the command available on my path. After installing as root I get the following error message:

Traceback (most recent call last):
  File "/usr/bin/frogmouth", line 5, in <module>
    from frogmouth.app.app import run
  File "/home/romano/.local/lib/python3.11/site-packages/frogmouth/app/__init__.py", line 3, in <module>
    from .app import run
  File "/home/romano/.local/lib/python3.11/site-packages/frogmouth/app/app.py", line 6, in <module>
    from textual import __version__ as textual_version  # pylint: disable=no-name-in-module
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ImportError: cannot import name '__version__' from 'textual' (unknown location)

**Comment by sanders41** [comment]
I am on Arch and can confirm Frogmouth works without error with `pipx`

**Comment by davep** [comment]
Thanks @sanders41

**Comment by davep** [comment]
@RomanoZumbe Is this still an issue you have? How did you get on with the suggestion made above a couple of weeks ago?

**Comment by Sush-ruta** [comment]
@davep Installing via AUR gives the `No module named 'frogmouth'` error. Installing via `pipx` works flawlessly. :)

**Comment by Sush-ruta** [comment]
@davep This is the [AUR PKGBUILD script](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=frogmouth). I posted a [comment](https://aur.archlinux.org/packages/frogmouth#comment-917521) highlighting the problem. Hope something comes out of this.

**Comment by davep** [comment]
@Sush-ruta That's very kind of you, thank you.

**Comment by davep** [comment]
Closing as stale.
