### ISSUE TITLE
Bug: The local filesystem tree is doubling up on entries

### ISSUE THREAD

**Issue by davep** [Textualize/frogmouth#50]
Mentioned in a video on YouTube. The content of the local file view is doubling up the entries for some reason:

<img width="967" alt="Screenshot 2023-05-25 at 11 03 26" src="https://github.com/Textualize/frogmouth/assets/28237/1f5c5cab-cf5e-49f2-b961-2715cd05f06e">

**Comment by davep** [comment]
Weird. My initial suspicion was something relating to the recent changes to `DirectoryTree` and perhaps the use of a filter; so I removed the filter for a moment, ran up the application, and it fixed the issue. So I put the filer back, ran up the application, and...

<img width="914" alt="Screenshot 2023-05-25 at 12 50 02" src="https://github.com/Textualize/frogmouth/assets/28237/82f5c4df-d10c-459d-a73c-680df6df4f58">

So now I *can't* actually recreate the issue any more!

**Comment by davep** [comment]
Recreating this is a bit hit-and-miss. On my own M2 Pro Mac Mini I *can* generally recreate this if I run the `pipx`-installed version, but if I run a "local" copy from the repo I can never reproduce it.

I do, however, have a hypothesis as to what might be going on. The recent changes to `DirectoryTree` in Textual itself, to load directories in the background, does have a possible window of opportunity whereby the `root` of the tree could end up getting loaded twice, in an additive way. I'm struggling to think of a way of forcing that to happen, but I think there's a chance it could and it would explain what I'm seeing here.

**Comment by willmcgugan** [comment]
Assuming fix. Unable to reproduce with latest Textual.
