### ISSUE TITLE
Unable to open relative images / resources when md file is not in current dir

### ISSUE THREAD

**Issue by jamescooke** [Textualize/frogmouth#52]
## Current behaviour

Frogmouth is not able to open resources relative to the current markdown file when that is not in the current directory. For example, for a file and image in a `doc` directory:

```sh
mkdir doc
curl https://placekitten.com/100/100 > doc/cat.png
cat > doc/README.md
```

```md
# Hello

[Some image](cat.png)
```

```sh
frogmouth doc/README.md
```

Clicking on the "Some image" link brings up a "Does not exist" box:

![Screenshot from 2023-05-27 23-19-45](https://github.com/Textualize/frogmouth/assets/781059/a6e3e31b-fb2b-4bc7-803f-7de2330fc49c)

## Expected behaviour

Browser window opens with the image.

This behaviour happens when frogmouth runs in the `doc` directory, so it's able to open files when they're in the current dir.

```sh
cd doc
frogmouth README.md
```

However, when opening files by passing a file in a different directory, or using the navigation to load a file in an alternate directory, relative paths from markdown no longer work.

**Comment by davep** [comment]
Good catch! And thank you for the very clear report/reproduction steps too.

Bonus points for including kittens!

**Comment by davep** [comment]
#53 should address this (looking good testing here). Will be in the next release.

Thanks again for raising this.

**Comment by jamescooke** [comment]
Thanks @davep - I've installed `main` and got the relatively linked images working in my local docs now 🎉

**Comment by davep** [comment]
Thanks for confirming. 🙂
