### ISSUE TITLE
Feature Request: browse any link

### ISSUE THREAD

**Issue by octoshrimpy** [Textualize/frogmouth#64]
Leverage https://pypi.org/project/pyhtml2md/ to convert any non-.md url into a markdown file and then render. also, handle any navigation to convert the nav-to page to md and render that. 

Literally a TUI html-to-markdown browser

**Comment by davep** [comment]
I'm not wholly convinced that this is a good idea, but also not wholly opposed to it either. At first glance I also wonder how portable the library is. I don't think we'll dive into this any time just yet, but I'll keep the issue kicking around and see how we feel about it longer-term.

Eg: my own preference as a user of Frogmouth would be that it *doesn't* keep me in the terminal when heading off to HTML (or other) documents, but I can appreciate I'm a sample of one.
