### ISSUE TITLE
“Error loading the local document”

### ISSUE THREAD

**Issue by mBaratta96** [Textualize/frogmouth#74]
Hello,

Wonderful app, but recently, it does this strange behavior each time I launch it to open a file:

![1691399656](https://github.com/Textualize/frogmouth/assets/37810930/d2a9a7b6-3996-4afc-917e-9b11cc02b638)

- Version is 0.8.0
- Installed with pip3
- Python version is 3.10.12
- Ubuntu 22.04.3 LTS

Thanks!

**Comment by davep** [comment]
Good catch. Recently we updated Textual's markdown viewer so that the `load` method doesn't return `True` or `False` but instead raises an error. Frogmouth is still working with the old behaviour. Easy fix to make so I'll sort that.

**Comment by davep** [comment]
Fixed via #75. Within the next hour or so a new release will go out. Thanks again for the report, really helpful!

**Comment by davep** [comment]
0.9.0 is now on PyPi. :-)
