### ISSUE TITLE
Please allow Textual version installed to roll forwards and not be pinned to `0.43`

### ISSUE THREAD

**Issue by jamescooke** [Textualize/frogmouth#94]
## Current behaviour

Textual is pinned with a poetry caret requirement in `pyproject.toml`:

```
textual = "^0.43.0"
```

The latest version of which is https://pypi.org/project/textual/0.43.2/ released 29th November 2023.

This is annoying / jarring because:
* Textual is moving forwards rapidly (we want the new shiny in Frogmouth too)
* Bumping textual requires a PR like https://github.com/Textualize/frogmouth/pull/89 - extra effort when there appear to be no breaking changes.
* "Standard" python behaviour is to install latest versions of requirements - for example Textual itself pulls the latest version of `rich` https://github.com/Textualize/textual/blob/main/pyproject.toml#L45

## Expected behaviour

Soften the requirement on Textual so clients / users can get the latest version of Textual when they install Frogmouth - maybe something like:

```
textual = ">=0.43.0"
```

Or

```
textual = "^0"
```

**Comment by davep** [comment]
This stems from a period when Textual was going through quite a few breaking changes, and needing to remember to reevaluate Frogmouth in the light of those changes wasn't a priority (and was far more extra effort than bumping the pin on occasion). I suspect we're more or less at a point where we can relax this.

**Comment by davep** [comment]
Just to update that I've reverted this change, for the moment, but will go back to this approach again soon. See #99 for context.
